services:
  frontend:
    build: .
    container_name: react_frontend
    ports:
      - "${VITE_PORT_EXPORT_REACT:-5173}:${VITE_PORT_DEFAULT_REACT:-5173}"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  node_modules:
