services:
  frontend:
    build: .
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  node_modules:
